import type { Business } from "@/types/business";

const MOCK_BUSINESSES: Record<string, Business> = {
  "biz-1": {
    id: "biz-1",
    name: "Studio Harmonii – Centrum Wellness",
    tagline: "Umysł, ciało i dusza — wszystko w jednym miejscu",
    description:
      "Studio Harmonii to wiodące krakowskie centrum wellness oferujące jogę, medytację, fitness i warsztaty kreatywne. Założone w 2018 roku, rozrosło się w tętniącą życiem społeczność ponad 2000 członków, którzy dzielą pasję do rozwoju osobistego i dobrego samopoczucia. Nasi instruktorzy światowej klasy wnoszą dekady łącznego doświadczenia w różnych dziedzinach.",
    category: "Wellness & Fitness",
    coverImage:
      "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&h=500&fit=crop",
    logo: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?w=200&h=200&fit=crop&crop=center",
    rating: 4.8,
    reviewCount: 312,
    verified: true,
    address: "ul. Dietla 50, 31-039 Kraków",
    coordinates: { lat: 50.0547, lng: 19.9421 },
    locations: [
      {
        id: "loc-1",
        name: "Main Studio",
        address: "ul. Dietla 50, 31-039 Kraków",
        coordinates: { lat: 50.0547, lng: 19.9421 },
      },
    ],
    hours: [
      { day: "Poniedziałek", open: "6:00", close: "21:00" },
      { day: "Wtorek", open: "6:00", close: "21:00" },
      { day: "Środa", open: "6:00", close: "21:00" },
      { day: "Czwartek", open: "6:00", close: "21:00" },
      { day: "Piątek", open: "6:00", close: "20:00" },
      { day: "Sobota", open: "7:00", close: "18:00" },
      { day: "Niedziela", open: "8:00", close: "17:00" },
    ],
    contact: {
      phone: "+48 12 345 67 89",
      email: "kontakt@studioharmonii.pl",
      website: "www.studioharmonii.pl",
    },
    social: {
      instagram: "@studioharmonii",
      facebook: "StudioHarmoniiKrakow",
    },
    activities: [
      {
        id: "act-1",
        title: "Poranna Joga Vinyasa",
        description:
          "Rozpocznij dzień ożywczą sesją jogi odpowiednią dla każdego poziomu.",
        category: "fitness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 124,
        price: "$",
        priceAmount: 15,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["morning"],
        spotsLeft: 5,
        businessId: "biz-1",
        instructorId: "inst-1",
      },
      {
        id: "act-2",
        title: "Medytacja i Uważność",
        description:
          "Znajdź spokój i jasność poprzez prowadzone praktyki medytacyjne.",
        category: "wellness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 198,
        price: "$",
        priceAmount: 12,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["morning", "evening"],
        businessId: "biz-1",
        instructorId: "inst-1",
      },
      {
        id: "act-3",
        title: "Power Pilates",
        description:
          "Zbuduj siłę core i elastyczność na naszych dynamicznych zajęciach Pilates.",
        category: "fitness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop",
        rating: 4.6,
        reviewCount: 87,
        price: "$",
        priceAmount: 18,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["morning", "afternoon"],
        businessId: "biz-1",
        instructorId: "inst-2",
      },
      {
        id: "act-4",
        title: "Oddech i Kąpiel Dźwiękowa",
        description:
          "Doświadcz głębokiego relaksu z prowadzonymi technikami oddechowymi i misami kryształowymi.",
        category: "wellness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 56,
        price: "$$",
        priceAmount: 25,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["evening", "weekend"],
        spotsLeft: 3,
        businessId: "biz-1",
        instructorId: "inst-3",
      },
      {
        id: "act-5",
        title: "Łagodny Stretching dla Seniorów",
        description:
          "Ćwiczenia rozciągające o niskim obciążeniu zaprojektowane dla starszych dorosłych.",
        category: "wellness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 43,
        price: "$",
        priceAmount: 10,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["morning"],
        businessId: "biz-1",
        instructorId: "inst-4",
      },
      {
        id: "act-6",
        title: "Vinyasa Flow Zaawansowane",
        description:
          "Wyzwij siebie zaawansowanymi sekwencjami i inwersami.",
        category: "fitness",
        provider: { name: "Studio Harmonii" },
        image:
          "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop",
        rating: 4.7,
        reviewCount: 72,
        price: "$$",
        priceAmount: 20,
        distance: 0,
        location: "Studio Harmonii",
        timeSlots: ["afternoon"],
        businessId: "biz-1",
        instructorId: "inst-5",
      },
    ],
    instructors: [
      {
        id: "inst-1",
        name: "Karolina Nowak",
        title: "Instruktorka Jogi i Medytacji",
        avatar:
          "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
        experience: "10 lat doświadczenia",
        bio: "Karolina prowadzi zajęcia jogi i medytacji od ponad 10 lat, łącząc tradycyjne techniki z nowoczesnym podejściem.",
        verified: true,
        specialty: "Joga i Medytacja",
        rating: 4.9,
      },
      {
        id: "inst-2",
        name: "Marek Jabłoński",
        title: "Instruktor Pilates i Fitness",
        avatar:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
        experience: "8 lat doświadczenia",
        bio: "Marek specjalizuje się w Pilates i treningu funkcjonalnym, pomagając klientom budować siłę i elastyczność.",
        verified: true,
        specialty: "Pilates i Fitness",
        rating: 4.8,
      },
      {
        id: "inst-3",
        name: "Agnieszka Wiśniewska",
        title: "Terapeutka Dźwiękiem",
        avatar:
          "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
        experience: "6 lat doświadczenia",
        bio: "Agnieszka jest certyfikowaną terapeutką dźwiękiem, prowadzącą sesje kąpieli dźwiękowych z misami kryształowymi.",
        verified: true,
        specialty: "Kąpiel Dźwiękowa",
        rating: 4.9,
      },
      {
        id: "inst-4",
        name: "Tomasz Górski",
        title: "Instruktor Technik Oddechowych",
        avatar:
          "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
        experience: "12 lat doświadczenia",
        bio: "Tomasz jest ekspertem w technikach oddechowych i prowadzi zajęcia rozciągające dla osób starszych.",
        verified: true,
        specialty: "Techniki Oddechowe",
        rating: 4.7,
      },
      {
        id: "inst-5",
        name: "Ewa Kowalczyk",
        title: "Instruktorka Vinyasa Flow",
        avatar:
          "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
        experience: "7 lat doświadczenia",
        bio: "Ewa specjalizuje się w zaawansowanych sekwencjach Vinyasa Flow i inwersach.",
        verified: true,
        specialty: "Vinyasa Flow",
        rating: 4.8,
      },
    ],
    reviews: [
      {
        id: "br-1",
        authorName: "Joanna M.",
        authorInitials: "JM",
        date: "5 stycznia 2025",
        rating: 5,
        text: "Studio Harmonii całkowicie zmieniło moją codzienną rutynę. Poranne zajęcia jogi to idealny sposób na rozpoczęcie dnia, a instruktorzy są kompetentni i zachęcający. Przestrzeń jest piękna i uspokajająca.",
      },
      {
        id: "br-2",
        authorName: "Tomek L.",
        authorInitials: "TL",
        date: "18 grudnia 2024",
        rating: 5,
        text: "Wypróbowałem wiele studiów w Krakowie i to wyróżnia się jakością instrukcji oraz ciepłą społecznością. Sesje kąpieli dźwiękowej są niesamowite — naprawdę wyjątkowe doświadczenie.",
      },
      {
        id: "br-3",
        authorName: "Priya S.",
        authorInitials: "PS",
        date: "30 listopada 2024",
        rating: 4,
        text: "Świetna różnorodność zajęć i bardzo czyste obiekty. Parking bywa problematyczny, ale studio jest warte wizyty. Zajęcia Pilates z Markiem są szczególnie dobre.",
      },
      {
        id: "br-4",
        authorName: "Krzysztof W.",
        authorInitials: "KW",
        date: "10 listopada 2024",
        rating: 5,
        text: "Sesje oddechowe tutaj zmieniły moją perspektywę na zarządzanie stresem. Tomasz jest niesamowitym instruktorem. Gorąco polecam każdemu, kto zmaga się z lękiem lub wypaleniem.",
      },
    ],
    ratingDistribution: [
      { stars: 5, percentage: 82 },
      { stars: 4, percentage: 12 },
      { stars: 3, percentage: 4 },
      { stars: 2, percentage: 1 },
      { stars: 1, percentage: 1 },
    ],
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&h=300&fit=crop",
        alt: "Zajęcia jogi w toku",
        caption: "Poranna Joga",
      },
      {
        src: "https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&h=300&fit=crop",
        alt: "Sesja kąpieli dźwiękowej",
        caption: "Sala Dźwięków",
      },
      {
        src: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop",
        alt: "Zajęcia Pilates na reformerze",
        caption: "Studio Pilates",
      },
      {
        src: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop",
        alt: "Przestrzeń medytacyjna",
        caption: "Ogród Medytacji",
      },
      {
        src: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop",
        alt: "Recepcja studia",
        caption: "Strefa Powitalna",
      },
      {
        src: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop",
        alt: "Zajęcia grupowe fitness",
        caption: "Energia Społeczności",
      },
    ],
  },
  "biz-2": {
    id: "biz-2",
    name: "Centrum Szachowe Kraków",
    tagline: "Strategia, taktyka i pasja — szachy dla każdego",
    description:
      "Centrum Szachowe Kraków to wiodący klub szachowy oferujący profesjonalną naukę gry w szachy dla dzieci, młodzieży i dorosłych. Prowadzimy kursy od poziomu początkującego po przygotowanie turniejowe. Nasi instruktorzy to doświadczeni szachiści z tytułami FIDE, którzy dzielą się swoją pasją i wiedzą z uczniami.",
    category: "Education",
    coverImage:
      "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=1200&h=500&fit=crop",
    logo: "https://images.unsplash.com/photo-1560174038-da43ac74f01b?w=200&h=200&fit=crop&crop=center",
    rating: 4.9,
    reviewCount: 128,
    verified: true,
    address: "ul. Floriańska 30, 31-021 Kraków",
    coordinates: { lat: 50.0647, lng: 19.9381 },
    locations: [
      {
        id: "loc-2",
        name: "Sala Główna",
        address: "ul. Floriańska 30, 31-021 Kraków",
        coordinates: { lat: 50.0647, lng: 19.9381 },
      },
    ],
    hours: [
      { day: "Poniedziałek", open: "9:00", close: "20:00" },
      { day: "Wtorek", open: "9:00", close: "20:00" },
      { day: "Środa", open: "9:00", close: "20:00" },
      { day: "Czwartek", open: "9:00", close: "20:00" },
      { day: "Piątek", open: "9:00", close: "18:00" },
      { day: "Sobota", open: "10:00", close: "16:00" },
      { day: "Niedziela", open: "10:00", close: "14:00" },
    ],
    contact: {
      phone: "+48 12 987 65 43",
      email: "kontakt@szachykrakow.pl",
      website: "www.szachykrakow.pl",
    },
    social: {
      instagram: "@szachykrakow",
      facebook: "CentrumSzachoweKrakow",
    },
    activities: [
      {
        id: "act-7",
        title: "Klub Szachowy Mistrzów: Strategia i Taktyka",
        description:
          "Odblokuj swój potencjał w Klubie Szachowym Mistrzów. Dla graczy średniozaawansowanych.",
        category: "education",
        provider: { name: "Centrum Szachowe Kraków" },
        image:
          "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 128,
        price: "$$",
        priceAmount: 25,
        distance: 0,
        location: "Centrum Szachowe Kraków",
        timeSlots: ["morning", "afternoon"],
        spotsLeft: 4,
        businessId: "biz-2",
        instructorId: "inst-6",
      },
      {
        id: "act-8",
        title: "Szachy dla Początkujących",
        description:
          "Łagodne wprowadzenie do szachów dla dzieci i dorosłych bez doświadczenia.",
        category: "education",
        provider: { name: "Centrum Szachowe Kraków" },
        image:
          "https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=400&h=300&fit=crop",
        rating: 4.8,
        reviewCount: 76,
        price: "$",
        priceAmount: 15,
        distance: 0,
        location: "Centrum Szachowe Kraków",
        timeSlots: ["afternoon", "weekend"],
        spotsLeft: 8,
        businessId: "biz-2",
        instructorId: "inst-6",
      },
      {
        id: "act-9",
        title: "Intensywne Przygotowanie Turniejowe",
        description:
          "Intensywne przygotowanie do nadchodzących turniejów rankingowych. Partie na czas i analiza po partii.",
        category: "education",
        provider: { name: "Centrum Szachowe Kraków" },
        image:
          "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=400&h=300&fit=crop",
        rating: 4.9,
        reviewCount: 42,
        price: "$$$",
        priceAmount: 50,
        distance: 0,
        location: "Centrum Szachowe Kraków",
        timeSlots: ["weekend"],
        businessId: "biz-2",
        instructorId: "inst-6",
      },
    ],
    instructors: [
      {
        id: "inst-6",
        name: "Arcymistrz Aleksander Nowak",
        title: "Instruktor Szachowy i Trener Turniejowy",
        avatar:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
        experience: "15 lat doświadczenia",
        bio: "Aleksander wyszkolił ponad 500 uczniów do sukcesów turniejowych w całej Polsce. Z najwyższym rankingiem FIDE 2580.",
        verified: true,
        specialty: "Szachy Strategiczne",
        rating: 4.9,
      },
    ],
    reviews: [
      {
        id: "br-5",
        authorName: "Marek Kowalski",
        authorInitials: "MK",
        date: "15 października 2024",
        rating: 5,
        text: "Aleksander jest niesamowitym mentorem. Ranking mojego syna poprawił się o ponad 200 punktów w zaledwie dwa miesiące.",
      },
      {
        id: "br-6",
        authorName: "Elena K.",
        authorInitials: "EK",
        date: "28 września 2024",
        rating: 5,
        text: "Świetny program skupiający się na końcówkach, które większość innych klubów ignoruje. Gorąco polecam.",
      },
      {
        id: "br-7",
        authorName: "Anna J.",
        authorInitials: "AJ",
        date: "20 sierpnia 2024",
        rating: 4,
        text: "Bardzo podobało mi się ustrukturyzowane podejście. Moja córka przeszła od zera do pierwszego turnieju w zaledwie 3 miesiące.",
      },
    ],
    ratingDistribution: [
      { stars: 5, percentage: 90 },
      { stars: 4, percentage: 8 },
      { stars: 3, percentage: 2 },
      { stars: 2, percentage: 0 },
      { stars: 1, percentage: 0 },
    ],
    gallery: [
      {
        src: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400&h=300&fit=crop",
        alt: "Sala szachowa",
        caption: "Sala Główna",
      },
      {
        src: "https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=400&h=300&fit=crop",
        alt: "Uczniowie współpracują nad strategią",
        caption: "Wspólna Analiza",
      },
      {
        src: "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=400&h=300&fit=crop",
        alt: "Praktyka turniejowa",
        caption: "Turnieje Próbne",
      },
      {
        src: "https://images.unsplash.com/photo-1560174038-da43ac74f01b?w=400&h=300&fit=crop",
        alt: "Instruktor udziela informacji zwrotnej",
        caption: "Indywidualne Wskazówki",
      },
    ],
  },
};

export async function getBusinessById(
  id: string
): Promise<Business | null> {
  await new Promise((resolve) => setTimeout(resolve, 600));
  return MOCK_BUSINESSES[id] ?? null;
}
