import type { InstructorAffiliation, CalendarEntry, SlotProposal } from "@/types/affiliation";

export const MOCK_AFFILIATIONS: InstructorAffiliation[] = [
  {
    instructorId: "inst-6",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "active",
    role: "contractor",
    startDate: "2023-09-01",
  },
  {
    instructorId: "inst-6",
    businessId: "biz-3",
    businessName: "Akademia Umysłu Wrocław",
    status: "pending",
    role: "contractor",
    startDate: "2026-02-15",
  },
  {
    instructorId: "inst-6",
    businessId: "biz-4",
    businessName: "Klub Szachowy Warszawa",
    status: "ended",
    role: "contractor",
    startDate: "2022-01-10",
    endDate: "2023-06-30",
  },
  {
    instructorId: "inst-6",
    businessId: "biz-5",
    businessName: "Akademia Gier Planszowych",
    status: "active",
    role: "contractor",
    startDate: "2025-06-01",
  },
  {
    instructorId: "inst-6",
    businessId: "biz-6",
    businessName: "Chess Academy Online",
    status: "pending",
    role: "contractor",
    startDate: "2026-02-20",
  },
  {
    instructorId: "inst-6",
    businessId: "biz-7",
    businessName: "Szkoła Myślenia Lateralnego",
    status: "ended",
    role: "contractor",
    startDate: "2024-01-15",
    endDate: "2025-04-30",
  },
  // ── inst-1 affiliations ──
  {
    instructorId: "inst-1",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "active",
    role: "contractor",
    startDate: "2022-03-01",
  },
  {
    instructorId: "inst-1",
    businessId: "biz-8",
    businessName: "Yoga Space Katowice",
    status: "active",
    role: "contractor",
    startDate: "2025-09-01",
  },
  {
    instructorId: "inst-1",
    businessId: "biz-9",
    businessName: "Mindful Studio Gdańsk",
    status: "pending",
    role: "contractor",
    startDate: "2026-02-20",
  },
  {
    instructorId: "inst-1",
    businessId: "biz-10",
    businessName: "Zen Garden Retreat",
    status: "ended",
    role: "contractor",
    startDate: "2023-05-01",
    endDate: "2024-12-31",
  },
];

export const MOCK_CALENDAR_ENTRIES: CalendarEntry[] = [
  // ── Today (Mar 1, Sunday – prev week) ──
  {
    id: "cal-today",
    instructorId: "inst-6",
    activityId: "act-f1",
    activityTitle: "Indywidualne Lekcje Szachowe",
    status: "confirmed",
    date: "2026-03-01",
    startTime: "11:00",
    endTime: "12:30",
  },
  // ── Week Mar 2–8 (Mon–Sun) ──
  // Monday Mar 2
  {
    id: "cal-9",
    instructorId: "inst-6",
    activityId: "act-8",
    activityTitle: "Szachy dla Początkujących",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-02",
    startTime: "09:00",
    endTime: "10:30",
    recurring: true,
  },
  // Tuesday Mar 3
  {
    id: "cal-1",
    instructorId: "inst-6",
    activityId: "act-f1",
    activityTitle: "Indywidualne Lekcje Szachowe",
    status: "confirmed",
    date: "2026-03-03",
    startTime: "10:00",
    endTime: "11:30",
    recurring: true,
  },
  {
    id: "cal-2",
    instructorId: "inst-6",
    activityId: "act-f2",
    activityTitle: "Szachy Online – Kurs Strategii",
    status: "confirmed",
    date: "2026-03-03",
    startTime: "16:00",
    endTime: "17:30",
    recurring: true,
  },
  {
    id: "cal-4",
    instructorId: "inst-6",
    activityId: "act-7",
    activityTitle: "Klub Szachowy Mistrzów: Strategia i Taktyka",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-03",
    startTime: "14:00",
    endTime: "16:00",
    recurring: true,
  },
  // Wednesday Mar 4
  {
    id: "cal-5",
    instructorId: "inst-6",
    activityId: "act-8",
    activityTitle: "Szachy dla Początkujących",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-04",
    startTime: "14:00",
    endTime: "16:00",
    recurring: true,
  },
  // Thursday Mar 5
  {
    id: "cal-3",
    instructorId: "inst-6",
    activityId: "act-f1",
    activityTitle: "Indywidualne Lekcje Szachowe",
    status: "confirmed",
    date: "2026-03-05",
    startTime: "10:00",
    endTime: "11:30",
    recurring: true,
  },
  // Friday Mar 6
  {
    id: "cal-10",
    instructorId: "inst-6",
    activityId: "act-7",
    activityTitle: "Klub Szachowy Mistrzów: Strategia i Taktyka",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-06",
    startTime: "10:00",
    endTime: "12:00",
    recurring: true,
  },
  {
    id: "cal-11",
    instructorId: "inst-6",
    activityId: "act-f2",
    activityTitle: "Szachy Online – Kurs Strategii",
    status: "confirmed",
    date: "2026-03-06",
    startTime: "15:00",
    endTime: "16:30",
    recurring: true,
  },
  // Saturday Mar 7
  {
    id: "cal-8",
    instructorId: "inst-6",
    activityId: "act-f2",
    activityTitle: "Szachy Online – Kurs Strategii",
    status: "cancelled",
    date: "2026-03-07",
    startTime: "16:00",
    endTime: "17:30",
  },
  // Sunday Mar 8
  {
    id: "cal-6",
    instructorId: "inst-6",
    activityId: "act-9",
    activityTitle: "Intensywne Przygotowanie Turniejowe",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-08",
    startTime: "10:00",
    endTime: "14:00",
    recurring: true,
  },
  // ── Week Mar 9–15 (Mon–Sun) ──
  // Monday Mar 9
  {
    id: "cal-12",
    instructorId: "inst-6",
    activityId: "act-f1",
    activityTitle: "Indywidualne Lekcje Szachowe",
    status: "confirmed",
    date: "2026-03-09",
    startTime: "10:00",
    endTime: "11:30",
    recurring: true,
  },
  // Tuesday Mar 10
  {
    id: "cal-7",
    instructorId: "inst-6",
    activityId: "act-10",
    activityTitle: "Warsztaty Szachowe dla Dzieci",
    businessId: "biz-3",
    businessName: "Akademia Umysłu Wrocław",
    status: "pending_approval",
    date: "2026-03-10",
    startTime: "09:00",
    endTime: "11:00",
  },
  // Wednesday Mar 11
  {
    id: "cal-13",
    instructorId: "inst-6",
    activityId: "act-8",
    activityTitle: "Szachy dla Początkujących",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-11",
    startTime: "14:00",
    endTime: "16:00",
    recurring: true,
  },
  // Friday Mar 13
  {
    id: "cal-14",
    instructorId: "inst-6",
    activityId: "act-f1",
    activityTitle: "Indywidualne Lekcje Szachowe",
    status: "confirmed",
    date: "2026-03-13",
    startTime: "10:00",
    endTime: "11:30",
    recurring: true,
  },
  {
    id: "cal-15",
    instructorId: "inst-6",
    activityId: "act-7",
    activityTitle: "Klub Szachowy Mistrzów: Strategia i Taktyka",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    status: "confirmed",
    date: "2026-03-13",
    startTime: "14:00",
    endTime: "16:00",
    recurring: true,
  },
  // ── inst-1 calendar entries ──
  // Today Mar 1 (Sunday)
  {
    id: "cal-i1-today",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-01",
    startTime: "08:00",
    endTime: "09:30",
  },
  // Monday Mar 2
  {
    id: "cal-i1-1",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-02",
    startTime: "07:00",
    endTime: "08:30",
    recurring: true,
  },
  {
    id: "cal-i1-2",
    instructorId: "inst-1",
    activityId: "act-2",
    activityTitle: "Medytacja i Uważność",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-02",
    startTime: "18:00",
    endTime: "19:00",
    recurring: true,
  },
  // Wednesday Mar 4
  {
    id: "cal-i1-3",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-04",
    startTime: "07:00",
    endTime: "08:30",
    recurring: true,
  },
  {
    id: "cal-i1-4",
    instructorId: "inst-1",
    activityId: "act-20",
    activityTitle: "Joga Kundalini",
    businessId: "biz-8",
    businessName: "Yoga Space Katowice",
    status: "confirmed",
    date: "2026-03-04",
    startTime: "11:00",
    endTime: "12:30",
    recurring: true,
  },
  // Thursday Mar 5
  {
    id: "cal-i1-5",
    instructorId: "inst-1",
    activityId: "act-2",
    activityTitle: "Medytacja i Uważność",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-05",
    startTime: "18:00",
    endTime: "19:00",
    recurring: true,
  },
  // Friday Mar 6
  {
    id: "cal-i1-6",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-06",
    startTime: "07:00",
    endTime: "08:30",
    recurring: true,
  },
  {
    id: "cal-i1-7",
    instructorId: "inst-1",
    activityId: "act-20",
    activityTitle: "Joga Kundalini",
    businessId: "biz-8",
    businessName: "Yoga Space Katowice",
    status: "cancelled",
    date: "2026-03-06",
    startTime: "11:00",
    endTime: "12:30",
  },
  // Saturday Mar 7
  {
    id: "cal-i1-8",
    instructorId: "inst-1",
    activityId: "act-21",
    activityTitle: "Weekend Yoga Retreat",
    status: "confirmed",
    date: "2026-03-07",
    startTime: "09:00",
    endTime: "11:00",
  },
  // Monday Mar 9
  {
    id: "cal-i1-9",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    status: "confirmed",
    date: "2026-03-09",
    startTime: "07:00",
    endTime: "08:30",
    recurring: true,
  },
  // Tuesday Mar 10
  {
    id: "cal-i1-10",
    instructorId: "inst-1",
    activityId: "act-22",
    activityTitle: "Warsztaty Oddechowe",
    businessId: "biz-9",
    businessName: "Mindful Studio Gdańsk",
    status: "pending_approval",
    date: "2026-03-10",
    startTime: "10:00",
    endTime: "12:00",
  },
];

export const MOCK_SLOT_PROPOSALS: SlotProposal[] = [
  {
    id: "prop-1",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    instructorId: "inst-6",
    activityId: "act-7",
    activityTitle: "Klub Szachowy Mistrzów: Strategia i Taktyka",
    date: "2026-03-12",
    startTime: "09:00",
    endTime: "11:00",
    status: "pending",
    proposedAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "prop-2",
    businessId: "biz-3",
    businessName: "Akademia Umysłu Wrocław",
    instructorId: "inst-6",
    activityId: "act-10",
    activityTitle: "Warsztaty Szachowe dla Dzieci",
    date: "2026-03-15",
    startTime: "10:00",
    endTime: "12:00",
    status: "pending",
    proposedAt: "2026-02-27T14:30:00Z",
  },
  {
    id: "prop-3",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    instructorId: "inst-6",
    activityId: "act-8",
    activityTitle: "Szachy dla Początkujących",
    date: "2026-03-06",
    startTime: "14:00",
    endTime: "16:00",
    status: "approved",
    proposedAt: "2026-02-25T09:00:00Z",
    respondedAt: "2026-02-25T12:00:00Z",
  },
  {
    id: "prop-4",
    businessId: "biz-2",
    businessName: "Centrum Szachowe Kraków",
    instructorId: "inst-6",
    activityId: "act-9",
    activityTitle: "Intensywne Przygotowanie Turniejowe",
    date: "2026-03-01",
    startTime: "10:00",
    endTime: "14:00",
    status: "rejected",
    proposedAt: "2026-02-20T16:00:00Z",
    respondedAt: "2026-02-21T08:00:00Z",
  },
  {
    id: "prop-5",
    businessId: "biz-5",
    businessName: "Akademia Gier Planszowych",
    instructorId: "inst-6",
    activityId: "act-11",
    activityTitle: "Wieczór z Grami Logicznymi",
    date: "2026-03-18",
    startTime: "18:00",
    endTime: "20:00",
    status: "pending",
    proposedAt: "2026-02-28T15:00:00Z",
  },
  {
    id: "prop-6",
    businessId: "biz-6",
    businessName: "Chess Academy Online",
    instructorId: "inst-6",
    activityId: "act-12",
    activityTitle: "Kurs Końcówek Szachowych",
    date: "2026-03-20",
    startTime: "16:00",
    endTime: "17:30",
    status: "approved",
    proposedAt: "2026-02-26T11:00:00Z",
    respondedAt: "2026-02-27T09:00:00Z",
  },
  {
    id: "prop-7",
    businessId: "biz-5",
    businessName: "Akademia Gier Planszowych",
    instructorId: "inst-6",
    activityId: "act-11",
    activityTitle: "Wieczór z Grami Logicznymi",
    date: "2026-03-04",
    startTime: "18:00",
    endTime: "20:00",
    status: "rejected",
    proposedAt: "2026-02-22T10:00:00Z",
    respondedAt: "2026-02-23T08:30:00Z",
  },
  // ── inst-1 slot proposals ──
  {
    id: "prop-i1-1",
    businessId: "biz-8",
    businessName: "Yoga Space Katowice",
    instructorId: "inst-1",
    activityId: "act-20",
    activityTitle: "Joga Kundalini",
    date: "2026-03-14",
    startTime: "11:00",
    endTime: "12:30",
    status: "pending",
    proposedAt: "2026-02-28T09:00:00Z",
  },
  {
    id: "prop-i1-2",
    businessId: "biz-9",
    businessName: "Mindful Studio Gdańsk",
    instructorId: "inst-1",
    activityId: "act-22",
    activityTitle: "Warsztaty Oddechowe",
    date: "2026-03-17",
    startTime: "10:00",
    endTime: "12:00",
    status: "pending",
    proposedAt: "2026-02-27T14:00:00Z",
  },
  {
    id: "prop-i1-3",
    businessId: "biz-1",
    businessName: "Studio Harmonii – Centrum Wellness",
    instructorId: "inst-1",
    activityId: "act-1",
    activityTitle: "Poranna Joga Vinyasa",
    date: "2026-03-08",
    startTime: "07:00",
    endTime: "08:30",
    status: "approved",
    proposedAt: "2026-02-24T10:00:00Z",
    respondedAt: "2026-02-24T15:00:00Z",
  },
  {
    id: "prop-i1-4",
    businessId: "biz-10",
    businessName: "Zen Garden Retreat",
    instructorId: "inst-1",
    activityId: "act-23",
    activityTitle: "Medytacja Vipassana",
    date: "2026-02-28",
    startTime: "09:00",
    endTime: "11:00",
    status: "rejected",
    proposedAt: "2026-02-20T08:00:00Z",
    respondedAt: "2026-02-21T10:00:00Z",
  },
];
